version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ipp-burger-app
    container_name: ipp-burger-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - ipp-network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: ipp-burger-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ipp-network

  db:
    image: postgres:15
    container_name: ipp-burger-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: burger_ipp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ipp-network

networks:
  ipp-network:
    driver: bridge

volumes:
  pgdata:
